development:
  clients:
    default:
      database: city_hive_proj
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: city_hive_proj_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
