[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.0" 